/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from "vue";

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Font: typeof import('./src/components/setting-inputs/Font.vue')['default']
    NumericalInput: typeof import('./src/components/setting-inputs/NumericalInput.vue')['default']
    ResultColumn: typeof import('./src/components/ResultColumn.vue')['default']
    Results: typeof import('./src/components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    TipInput: typeof import('./src/components/tips/TipInput.vue')['default']
    Tips: typeof import('./src/components/Tips.vue')['default']
  }
}

// For TSX support
declare global {
  const Font: (typeof import("./src/components/setting-inputs/Font.vue"))["default"];
  const NumericalInput: (typeof import("./src/components/setting-inputs/NumericalInput.vue"))["default"];
  const ResultColumn: (typeof import("./src/components/ResultColumn.vue"))["default"];
  const Results: (typeof import("./src/components/Results.vue"))["default"];
  const RouterLink: (typeof import("vue-router"))["RouterLink"];
  const RouterView: (typeof import("vue-router"))["RouterView"];
  const Settings: (typeof import("./src/components/Settings.vue"))["default"];
  const TipInput: (typeof import("./src/components/tips/TipInput.vue"))["default"];
  const Tips: (typeof import("./src/components/Tips.vue"))["default"];
}
